### ISSUE TITLE
killing the process while sealing leads to unrecoverable state

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/rust-fil-sector-builder#17]
### Description
If you start sealing a sector and then kill the process, the sectorbuilder will not attempt to keep sealing that sector when the process restarts. (even if explicitly told to via SealAllStagedSectors)

We should be able to recover from this somehow.

**Comment by whyrusleeping** [comment]
@laser @dignifiedquire any thoughts here? this is super inconvenient

**Comment by dignifiedquire** [comment]
:( will take a look later today if there is an easy fix

**Comment by whyrusleeping** [comment]
@dignifiedquire any update?
