### ISSUE TITLE
rust-fil-sector-builder build failed on filecoin_proofs dependency

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/rust-fil-sector-builder#65]
### Description

I got below error when I modify and build rust-fil-sector-builder project seperately,could you please give a hint how to figure out the dependency issue ?

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
  --> sector-builder/src/metadata_manager.rs:62:21
   |
62 |                     PrivateReplicaInfo::new_faulty(path_str, sector.comm_r)
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0061]: this function takes 3 parameters but 2 parameters were supplied
  --> sector-builder/src/metadata_manager.rs:64:21
   |
64 |                     PrivateReplicaInfo::new(path_str, sector.comm_r)
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters

error[E0026]: struct `filecoin_proofs::api::SealOutput` does not have a field named `comm_r_star`
   --> sector-builder/src/metadata_manager.rs:265:25
    |
265 |                         comm_r_star,
    |                         ^^^^^^^^^^^ struct `filecoin_proofs::api::SealOutput` does not have this field

error[E0027]: pattern does not mention field `p_aux`
   --> sector-builder/src/metadata_manager.rs:263:25
    |
263 |                       let SealOutput {
    |  _________________________^
264 | |                         comm_r,
265 | |                         comm_r_star,
266 | |                         comm_d,
...   |
269 | |                         piece_inclusion_proofs,
270 | |                     } = output;
    | |_____________________^ missing field `p_aux`

error[E0061]: this function takes 7 parameters but 6 parameters were supplied
   --> sector-builder/src/worker.rs:140:34
    |
140 |                       let result = filecoin_proofs::seal(
    |  __________________________________^
141 | |                         porep_config,
142 | |                         &staged_sector_path,
143 | |                         &sealed_sector_path,
...   |
146 | |                         &piece_lens,
147 | |                     );
    | |_____________________^ expected 7 parameters

error[E0061]: this function takes 9 parameters but 7 parameters were supplied
   --> sector-builder/src/worker.rs:168:34
    |
168 |                       let result = filecoin_proofs::get_unsealed_range(
    |  __________________________________^
169 | |                         porep_config,
170 | |                         &source_path,
171 | |                         &destination_path,
...   |
175 | |                         piece_len,
176 | |                     )
    | |_____________________^ expected 9 parameters

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0026, E0027, E0061.
For more information about an error, try `rustc --explain E0026`.
error: Could not compile `sector-builder`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name sector_builder sector-builder/src/lib.rs --color never --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="default"' --cfg 'feature="sled"' -C metadata=fea162a526965cb1 -C extra-filename=-fea162a526965cb1 --out-dir /Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps -L dependency=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps --extern bitvec=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libbitvec-d481ab8bd1dd787b.rmeta --extern blake2b_simd=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libblake2b_simd-740d0ab6addf08d2.rmeta --extern byteorder=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libbyteorder-f93db56241fd4c64.rmeta --extern failure=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libfailure-ee5cb5c63057afec.rmeta --extern filecoin_proofs=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libfilecoin_proofs-ceeb07c63c206343.rmeta --extern itertools=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libitertools-6acaf4cffbbb7020.rmeta --extern log=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/liblog-0e6cf52c55cdc3f8.rmeta --extern paired=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libpaired-b8f030c3f726d373.rmeta --extern rand=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/librand-136347a83479fc38.rmeta --extern rayon=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/librayon-fd3c2855b1a10af0.rmeta --extern serde=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libserde-f88ec84db48fd70e.rmeta --extern serde_cbor=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libserde_cbor-3ea4f13786b11d76.rmeta --extern serde_json=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libserde_json-187d2d04dee37a9d.rmeta --extern sled=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libsled-db9c61289ef867c3.rmeta --extern storage_proofs=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/deps/libstorage_proofs-e28f95e7632b949b.rmeta --print native-static-libs -L native=/Users/tshi/code/go/src/github.com/filecoin-project/rust-fil-sector-builder/target/release/build/backtrace-sys-4525db7521ece353/out` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed

### Acceptance criteria
NA.

### Risks + pitfalls
NA.

### Where to begin
NA.

**Comment by laser** [comment]
@taoshengshi - I am not able to reproduce your error. See the following log from my machine:

```bash
✔ /tmp
10:06 $ cd $(mktemp -d)
✔ /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6
10:06 $ git clone git@github.com:filecoin-project/rust-fil-sector-builder.git
Cloning into 'rust-fil-sector-builder'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 3731 (delta 11), reused 23 (delta 10), pack-reused 3701
Receiving objects: 100% (3731/3731), 877.98 KiB | 496.00 KiB/s, done.
Resolving deltas: 100% (2360/2360), done.
✔ /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6
10:06 $ cd rust-fil-sector-builder/
✔ /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6/rust-fil-sector-builder [master|✔]
10:06 $ git rev-parse HEAD
e52fe7818bc45e7ccefdab59f4598592e651efd3
✔ /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6/rust-fil-sector-builder [master|✔]
10:06 $ cargo check --all --examples --tests --bins
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.62
   Compiling autocfg v0.1.6
   Compiling byteorder v1.3.2
   Compiling proc-macro2 v0.4.30
   Compiling proc-macro2 v1.0.5
   Compiling unicode-xid v0.1.0
   Compiling unicode-xid v0.2.0
   Compiling arrayvec v0.4.11
   Compiling getrandom v0.1.12
   Compiling log v0.4.8
    Checking scopeguard v1.0.0
    Checking either v1.5.3
   Compiling syn v1.0.5
    Checking lazy_static v1.4.0
    Checking nodrop v0.1.13
    Checking smallvec v0.6.10
    Checking cfg-if v0.1.10
   Compiling cc v1.0.45
    Checking fnv v1.0.6
   Compiling typenum v1.11.2
   Compiling syn v0.15.44
    Checking slab v0.4.2
   Compiling core-foundation-sys v0.6.2
   Compiling version_check v0.1.5
   Compiling memchr v2.2.1
    Checking futures v0.1.29
    Checking ppv-lite86 v0.2.5
   Compiling serde v1.0.101
    Checking matches v0.1.8
    Checking rand_core v0.4.2
    Checking rustc-demangle v0.1.16
   Compiling httparse v1.3.4
    Checking arrayref v0.3.5
    Checking itoa v0.4.4
   Compiling failure_derive v0.1.5
   Compiling winapi v0.3.8
   Compiling ryu v1.0.0
   Compiling cgmath v0.16.1
   Compiling rayon-core v1.6.0
   Compiling bitflags v1.2.0
    Checking constant_time_eq v0.1.4
    Checking serde v0.8.23
    Checking approx v0.1.1
    Checking byte-tools v0.3.1
    Checking regex-syntax v0.6.12
    Checking percent-encoding v1.0.1
   Compiling crc32fast v1.2.0
    Checking indexmap v1.2.0
   Compiling glob v0.3.0
    Checking try-lock v0.2.2
    Checking percent-encoding v2.1.0
   Compiling unicode-width v0.1.6
    Checking remove_dir_all v0.5.2
    Checking quick-error v1.2.2
   Compiling native-tls v0.2.3
    Checking bit-vec v0.5.1
    Checking adler32 v1.0.4
    Checking opaque-debug v0.2.3
    Checking byteorder v0.5.3
    Checking termcolor v1.0.5
    Checking lazy_static v0.2.11
   Compiling ansi_term v0.11.0
    Checking linked-hash-map v0.5.2
   Compiling vec_map v0.8.1
   Compiling strsim v0.8.0
    Checking rgb v0.8.14
   Compiling encoding_rs v0.8.20
   Compiling cbindgen v0.9.1
    Checking rust-ini v0.13.0
   Compiling storage-proofs v0.6.2 (https://github.com/filecoin-project/rust-fil-proofs.git#64ece875)
    Checking fake-simd v0.1.2
    Checking mime v0.3.14
    Checking dtoa v0.4.4
   Compiling bindgen v0.49.2
   Compiling peeking_take_while v0.1.2
    Checking half v1.3.1
    Checking bitvec v0.5.0
   Compiling shlex v0.1.1
    Checking historian v4.0.3
   Compiling nix v0.10.0
    Checking same-file v1.0.5
    Checking bitvec v0.11.3
    Checking cast v0.2.2
    Checking void v1.0.2
    Checking bitflags v0.9.1
   Compiling semver v0.9.0
    Checking lock_api v0.3.1
    Checking thread_local v0.3.6
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling num-bigint v0.2.3
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling bincode v1.2.0
    Checking crossbeam-utils v0.6.6
    Checking try_from v0.3.2
    Checking itertools v0.8.0
    Checking unicode-normalization v0.1.8
   Compiling unicase v2.5.1
   Compiling error-chain v0.12.1
   Compiling nom v4.2.3
    Checking unicode-bidi v0.3.4
    Checking rand_core v0.3.1
    Checking c2-chacha v0.2.2
    Checking block-padding v0.1.4
   Compiling textwrap v0.11.0
    Checking humantime v1.3.0
   Compiling backtrace-sys v0.1.31
   Compiling libloading v0.5.2
    Checking miniz_oxide v0.3.3
   Compiling clang-sys v0.28.1
    Checking tokio-sync v0.1.6
    Checking yaml-rust v0.4.3
    Checking walkdir v2.2.9
   Compiling rustc_version v0.2.3
    Checking tokio-executor v0.1.8
    Checking crossbeam-queue v0.1.2
    Checking crossbeam-channel v0.3.9
    Checking serde_test v0.8.23
    Checking rand_xorshift v0.1.1
    Checking rand_hc v0.1.0
    Checking rand_isaac v0.1.1
    Checking criterion-plot v0.4.0
    Checking iovec v0.1.2
    Checking net2 v0.2.33
    Checking num_cpus v1.10.1
    Checking rand v0.4.6
    Checking rand_os v0.1.3
    Checking rand_jitter v0.1.4
    Checking time v0.1.42
    Checking atty v0.2.13
    Checking memmap v0.7.0
    Checking positioned-io v0.2.2
    Checking filetime v0.2.7
    Checking fs2 v0.4.3
    Checking xattr v0.2.2
    Checking ffi-toolkit v0.3.0
    Checking nix v0.9.0
    Checking blake2b_simd v0.5.8
    Checking blake2s_simd v0.5.8
    Checking want v0.2.0
   Compiling quote v0.6.13
   Compiling quote v1.0.2
   Compiling memoffset v0.5.1
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling hyper v0.12.35
    Checking security-framework-sys v0.3.1
    Checking core-foundation v0.6.4
    Checking fxhash v0.2.1
    Checking base64 v0.10.1
    Checking regex-automata v0.1.8
    Checking tokio-current-thread v0.1.6
    Checking tokio-timer v0.2.11
    Checking linked-hash-map v0.3.0
    Checking flate2 v1.0.12
    Checking idna v0.2.0
    Checking idna v0.1.5
    Checking generic-array v0.12.3
    Checking bytes v0.4.12
    Checking futures-cpupool v0.1.8
    Checking rand_core v0.5.1
    Checking mio v0.6.19
    Checking clap v2.33.0
    Checking aho-corasick v0.7.6
    Checking csv-core v0.1.6
    Checking tar v0.4.26
    Checking pbr v1.0.2
   Compiling syn v0.14.9
    Checking security-framework v0.3.1
    Checking num-traits v0.1.43
   Compiling mime_guess v2.0.1
    Checking backtrace v0.3.38
    Checking block-cipher-trait v0.6.2
    Checking digest v0.8.1
    Checking block-buffer v0.7.3
    Checking rand_chacha v0.2.1
    Checking rand_xoshiro v0.3.1
    Checking rand_os v0.2.2
    Checking url v2.1.0
    Checking tokio-io v0.1.12
    Checking string v0.2.1
    Checking tokio-buf v0.1.1
    Checking http v0.1.18
    Checking url v1.7.2
    Checking regex v1.3.1
   Compiling cexpr v0.3.5
    Checking uuid v0.7.4
    Checking chrono v0.4.9
    Checking aes-soft v0.3.3
    Checking block-modes v0.3.3
    Checking sha2 v0.8.0
    Checking rand v0.7.2
   Compiling synstructure v0.10.2
    Checking cookie v0.12.0
    Checking env_proxy v0.3.1
    Checking env_logger v0.6.2
    Checking serde-hjson v0.8.2
    Checking os_type v2.2.0
    Checking h2 v0.1.26
    Checking http-body v0.1.0
    Checking crossbeam-epoch v0.7.2
    Checking pipe-channel v1.2.2
   Compiling drop_struct_macro_derive v0.3.0
    Checking aes v0.3.2
   Compiling ff_derive v0.3.0
    Checking publicsuffix v1.5.3
    Checking tempfile v3.1.0
    Checking pretty_env_logger v0.3.1
    Checking winconsole v0.10.0
    Checking tokio-reactor v0.1.10
    Checking once_cell v0.2.4
    Checking crossbeam-deque v0.7.1
    Checking colored v1.8.0
    Checking tokio-threadpool v0.1.16
    Checking crossbeam v0.7.2
    Checking tokio-tcp v0.1.3
    Checking rayon v1.2.0
    Checking failure v0.1.5
    Checking tokio v0.1.22
   Compiling which v2.0.1
   Compiling serde_derive v1.0.101
    Checking ff v0.4.0
    Checking merkletree v0.10.0
    Checking hyper-tls v0.3.2
    Checking paired v0.15.1
    Checking toml v0.4.10
    Checking serde_json v1.0.41
    Checking hashbrown v0.3.1
    Checking serde_urlencoded v0.5.5
    Checking toml v0.5.3
    Checking serde_cbor v0.9.0
    Checking serde_bytes v0.11.2
    Checking bstr v0.2.8
    Checking pagecache v0.17.0
    Checking cookie_store v0.7.0
    Checking config v0.9.3
    Checking tinytemplate v1.0.2
    Checking csv v1.1.1
    Checking reqwest v0.9.21
    Checking bellperson v0.3.0
    Checking criterion v0.3.0
    Checking sled v0.24.1
    Checking fil-sapling-crypto v0.1.2
    Checking phase21 v0.3.2
   Compiling filecoin-proofs-ffi v0.7.3 (https://github.com/filecoin-project/rust-fil-proofs-ffi.git#d600fd2c)
   Compiling sector-builder-ffi v0.5.2 (/private/var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6/rust-fil-sector-builder/sector-builder-ffi)
    Checking filecoin-proofs v0.6.4 (https://github.com/filecoin-project/rust-fil-proofs.git#64ece875)
    Checking sector-builder v0.5.2 (/private/var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6/rust-fil-sector-builder/sector-builder)
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
    Finished dev [unoptimized + debuginfo] target(s) in 1m 56s
✔ /var/folders/8h/gmmbhq1s5tb8sk9011sy2wkw0000gn/T/tmp.ROcAo5o6/rust-fil-sector-builder [master|✔]
```

Would you please provide steps which I can use to reproduce this issue?

**Comment by taoshengshi** [comment]
@laser  Because I modify the dependency in cargo.toml to refer my private project, and got from @dignifiedquire  that the master of rust-fil-proofs is not compatible with the master of go-sectorbuilder, so I can find a way to pin the dependencies to a specific commit.  thanks a lot!
